apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-server-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/sqlserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-pv-claim
  labels:
    app: sql-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi