apiVersion: v1
kind: Service
metadata:
  name: sql-server
spec:
  type: NodePort
  selector:
    app: sql-server
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
spec:
  selector:
    matchLabels:
      app: sql-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - image: sql-server:latest
        name: sql-server
        imagePullPolicy: Never
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        ports:
        - containerPort: 1433
          name: sql-server
        volumeMounts:
        - name: sql-server-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-server-persistent-storage
        persistentVolumeClaim:
          claimName: sql-server-pv-claim



    